language: java
jdk:
  - openjdk11

before_install:
  - chmod +x gradlew

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r simpson-springboot2-webservice *
  - mkdir -p deploy
  - mv simpson-springboot2-webservice.zip deploy/simpson-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: simpson-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true # master branch외의 다른 브랜치 허용

notifications:
  email:
    recipients:
      - apvmffkdls@gmail.com
