server:
  port: 8081

spring:
  profiles:
    include: real-db, oauth
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc